import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { NextPage } from "next";
import { MouseEvent } from "react";

export default function Home() {
  // const [checked,setChecked]
  const handleClick = async (e: MouseEvent<HTMLInputElement>) => {
    console.log(e.currentTarget.value);
    const response = await fetch("/api/getUser", {
      method: "POST",
      body: JSON.stringify(e.currentTarget.value),
    });
    console.log(response);
    // const json = await response.json();

    // if (json.ok) {
    //   const { user } = json;
    //   console.log(JSON.stringify(user));
    // } else {
    //   const { code, details } = json.error;
    //   console.log(`Error! ${code}: ${details}`);
    // }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <label>
            <input type="radio" name="a" value="1" onClick={handleClick} />
          </label>

          <label>
            <input type="radio" name="b" value="2" onClick={handleClick} />
          </label>

          <label>
            <input type="radio" name="c" value="3" onClick={handleClick} />
          </label>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
