import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { NextPage } from "next";
import { MouseEvent, useState } from "react";
import { User } from "../generated/user_pb";

export default function Home() {
  const [user, setUser] = useState<User.AsObject>();
  const [currentId, setCurrentId] = useState<string>();
  const handleClick = async (e: MouseEvent<HTMLInputElement>) => {
    setCurrentId(e.currentTarget.value);
    const response = await fetch(`/api/getUser/${e.currentTarget.value}`);
    const json = await response.json();
    setUser(json.user);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <label>
            <input
              type="radio"
              name="a"
              value="1"
              onClick={handleClick}
              checked={currentId === "1"}
            />
          </label>

          <label>
            <input
              type="radio"
              name="b"
              value="2"
              onClick={handleClick}
              checked={currentId === "2"}
            />
          </label>

          <label>
            <input
              type="radio"
              name="c"
              value="3"
              onClick={handleClick}
              checked={currentId === "3"}
            />
          </label>
        </div>
        <span>{user?.id}</span>
        <span>{user?.name}</span>
      </main>
    </div>
  );
}
